# Generated by Django 2.1.4 on 2019-01-19 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('CrawlProject', '0003_auto_20190119_0833'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crawls',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crawl_name', models.CharField(max_length=30, verbose_name='爬虫名称')),
                ('crawl_file', models.FileField(max_length=50, upload_to='sfCrawl/', verbose_name='爬虫文件')),
                ('source', models.CharField(max_length=100, verbose_name='爬虫源网站')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建日期')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新日期')),
                ('project_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='CrawlProject.Project')),
            ],
        ),
    ]
