# Generated by Django 2.1.4 on 2019-01-19 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Crawls', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='crawls',
            options={'ordering': ['-update_time']},
        ),
        migrations.AlterModelTable(
            name='crawls',
            table='crawls',
        ),
    ]
