# Generated by Django 2.1.4 on 2019-02-14 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Crawls', '0002_auto_20190119_0835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crawls',
            name='project_id',
            field=models.ForeignKey(db_column='project_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='CrawlProject.Project'),
        ),
    ]
