# Generated by Django 2.1.4 on 2019-02-15 02:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Crawls', '0003_auto_20190214_0957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crawls',
            name='project_id',
            field=models.ForeignKey(db_column='project', null=True, on_delete=django.db.models.deletion.SET_NULL, to='CrawlProject.Project'),
        ),
    ]
