# Generated by Django 2.1.4 on 2019-01-18 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CrawlProject', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='project',
            table='project',
        ),
    ]
