# Generated by Django 2.1.4 on 2019-01-19 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CrawlProject', '0002_auto_20190118_1138'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-create_time']},
        ),
    ]
