# Generated by Django 2.1.4 on 2019-02-27 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CrawlProject', '0003_auto_20190119_0833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='code',
            field=models.CharField(max_length=10, unique=True, verbose_name='项目编码'),
        ),
    ]
